### PR TITLE
add snails' self-introduction and wishing_wall

### PR DESCRIPTION
**Pull request by ghost**
Add something about me. Please merge it. THX.

### CODE REVIEW

**Comment by Youngv** [comment]
I don't know why I have the permission to merge the commit, but what you have done is ok.

**Comment by hlee** [comment]
nice job~ guys

**Comment by perfectfoolish** [comment]
@snails  Thank you for helping me in RubyChina long long ago.

**Comment by ghost** [comment]
@perfectfoolish Me? I can't remember. But I am glad to helped someone. Best wished for U.

**Comment by perfectfoolish** [comment]
@snails https://ruby-china.org/topics/6566

**Pull request merged**
